name: Linters
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '!**.md'
      - '.github/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: run Flake8
        working-directory: ./src
        run: |
          flake8 .

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install isort
        run: |
          python -m pip install isort
      - name: Run isort
        uses: jamescurtin/isort-action@master
        with:
            sortPaths: "src"
